#
#
#server:
#  port: 8081
#
#spring:
#  shardingsphere:
#    datasource:
#      names: ds_0, ds_1
#      ds_0:
#        type: com.zaxxer.hikari.HikariDataSource
#        driverClassName: com.mysql.cj.jdbc.Driver
#        jdbcUrl: jdbc:mysql://localhost:3306/demo_ds_0?serverTimezone=UTC&useSSL=false&useUnicode=true&characterEncoding=UTF-8
#        username: root
#        password:
#      ds_1:
#        type: com.zaxxer.hikari.HikariDataSource
#        driverClassName: com.mysql.cj.jdbc.Driver
#        jdbcUrl: jdbc:mysql://localhost:3306/demo_ds_1?serverTimezone=UTC&useSSL=false&useUnicode=true&characterEncoding=UTF-8
#        username: root
#        password:
#    rules:
#      sharding:
#        tables:
#          ...
